package static

var (
	INVALID_PARAMS        = "ERR_001"
	INTERNAL_SERVER_ERROR = "ERR_002"
	USER_AUTHEN_ERROR     = "ERROR_003"
	USER_NOT_FOUND        = "ERROR_004"
	USER_WRONG_PASSWORD   = "ERROR_005"
)
