package static

var (
	INVALID_PARAMS          = "ERR_001"
	INTERNAL_SERVER_ERROR   = "ERR_002"
	USER_AUTHEN_ERROR       = "ERROR_003"
	USER_NOT_FOUND          = "ERROR_004"
	USER_WRONG_PASSWORD     = "ERROR_005"
	DOWNLOAD_TEMPLATE_ERROR = "ERROR_006"
	CANNOT_READ_FILE_ERROR  = "ERROR_007"
	FILE_NO_DATA_ERROR      = "ERROR_008"
	COLUMN_COUNT_INVALID    = "ERROR_009"
	COLUMN_NAME_INVALID     = "ERROR_010"
	CANNOT_LOAD_CONFIG      = "ERROR_011"
	ERROR_AMOUNT_OF_SEARCH  = "ERROR_12"
	GET_KEYWORD_ERROR       = "ERROR_13"
	UPLOAD_TEMPLATE_ERROR   = "ERROR_14"
)
